"""empty message

Revision ID: 1306a1652794
Revises: cc8efe50325c
Create Date: 2024-02-04 21:44:13.510021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1306a1652794'
down_revision = 'cc8efe50325c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sell', schema=None) as batch_op:
        batch_op.add_column(sa.Column('front_img', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('back_img', sa.String(length=300), nullable=False))
        batch_op.drop_column('goods_name')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.ENUM('1', '0'), server_default=sa.text("'0'"), nullable=False))

    with op.batch_alter_table('sell', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goods_name', mysql.VARCHAR(length=300), nullable=False))
        batch_op.drop_column('back_img')
        batch_op.drop_column('front_img')

    # ### end Alembic commands ###
