"""empty message

Revision ID: 258c626538af
Revises: a18a11cc7489
Create Date: 2025-04-24 08:36:01.624959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '258c626538af'
down_revision = 'a18a11cc7489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(length=300), nullable=False))
        batch_op.drop_column('filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', mysql.VARCHAR(length=300), nullable=False))
        batch_op.drop_column('img')

    # ### end Alembic commands ###
