"""empty message

Revision ID: 31b6f5564120
Revises: a240c71c3202
Create Date: 2025-04-27 21:07:49.877447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31b6f5564120'
down_revision = 'a240c71c3202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_name', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('seller_number', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('seller_number')
        batch_op.drop_column('seller_name')

    # ### end Alembic commands ###
