"""empty message

Revision ID: 34a603c92d2e
Revises: 31b6f5564120
Create Date: 2025-04-27 21:11:16.841888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34a603c92d2e'
down_revision = '31b6f5564120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_name', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('seller_number', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('seller_number')
        batch_op.drop_column('seller_name')

    # ### end Alembic commands ###
