"""empty message

Revision ID: 4435a8b96568
Revises: 
Create Date: 2025-04-23 22:00:36.887672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4435a8b96568'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('pwd', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('adverts',
    sa.Column('ads_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ads_company', sa.String(length=300), nullable=False),
    sa.Column('ads_cover', sa.String(length=100), nullable=True),
    sa.Column('ads_Link', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('ads_id')
    )
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('job',
    sa.Column('job_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_title', sa.String(length=300), nullable=False),
    sa.Column('job_state', sa.String(length=300), nullable=False),
    sa.Column('job_country', sa.String(length=300), nullable=False),
    sa.Column('salary_range', sa.String(length=300), nullable=False),
    sa.Column('employer', sa.String(length=300), nullable=False),
    sa.Column('working_hours', sa.String(length=300), nullable=False),
    sa.Column('job_link', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('front_img', sa.String(length=300), nullable=False),
    sa.Column('back_img', sa.String(length=300), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('delprice', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('seller_user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstname', sa.String(length=60), nullable=False),
    sa.Column('lastname', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('city', sa.String(length=300), nullable=True),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('phone', sa.BigInteger(), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=300), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('cart',
    sa.Column('cart_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('img', sa.String(length=300), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('goods_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goods_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('cart_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    op.drop_table('user')
    op.drop_table('product')
    op.drop_table('job')
    op.drop_table('category')
    op.drop_table('adverts')
    op.drop_table('admin')
    # ### end Alembic commands ###
