"""empty message

Revision ID: 464ed904f7cc
Revises: 327a176f6304
Create Date: 2024-01-27 17:41:24.744117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464ed904f7cc'
down_revision = '327a176f6304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_state', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('job_country', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('salary_range', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('working_hours', sa.String(length=300), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('working_hours')
        batch_op.drop_column('salary_range')
        batch_op.drop_column('job_country')
        batch_op.drop_column('job_state')

    # ### end Alembic commands ###
