"""empty message

Revision ID: 53d14a18d20b
Revises: 596dbb38b8ef
Create Date: 2025-08-06 13:06:33.446835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53d14a18d20b'
down_revision = '596dbb38b8ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('size')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', mysql.VARCHAR(length=300), nullable=False))

    # ### end Alembic commands ###
