"""empty message

Revision ID: 596dbb38b8ef
Revises: 71b858f049de
Create Date: 2025-08-06 12:35:43.053144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596dbb38b8ef'
down_revision = '71b858f049de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.String(length=300), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('size')

    # ### end Alembic commands ###
