"""empty message

Revision ID: 6e2d37daf8a6
Revises: 82b15acb9262
Create Date: 2024-01-27 17:55:49.625857

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e2d37daf8a6'
down_revision = '82b15acb9262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('job_qualification')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_qualification', mysql.VARCHAR(length=300), nullable=False))

    # ### end Alembic commands ###
