"""empty message

Revision ID: 759ecce07f66
Revises: 34a603c92d2e
Create Date: 2025-04-27 21:53:54.934210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759ecce07f66'
down_revision = '34a603c92d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=300), nullable=False))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=300), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('product_name')

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###
