"""empty message

Revision ID: 762058ea3316
Revises: 1306a1652794
Create Date: 2024-02-05 16:51:43.398394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762058ea3316'
down_revision = '1306a1652794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=300), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
