"""empty message

Revision ID: 7ca1caf83f7b
Revises: 759ecce07f66
Create Date: 2025-04-27 21:57:25.752460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ca1caf83f7b'
down_revision = '759ecce07f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('product_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_description', mysql.VARCHAR(length=500), nullable=True))

    # ### end Alembic commands ###
