"""empty message

Revision ID: 82b15acb9262
Revises: 464ed904f7cc
Create Date: 2024-01-27 17:45:27.974449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82b15acb9262'
down_revision = '464ed904f7cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('job_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_description', mysql.VARCHAR(length=300), nullable=False))

    # ### end Alembic commands ###
