"""empty message

Revision ID: 8794e358dda8
Revises: d1dfdea1c340
Create Date: 2025-08-06 07:40:37.311228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8794e358dda8'
down_revision = 'd1dfdea1c340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('firstname',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
        batch_op.alter_column('lastname',
               existing_type=mysql.VARCHAR(length=60),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=300),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=300),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('lastname',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
        batch_op.alter_column('firstname',
               existing_type=mysql.VARCHAR(length=60),
               nullable=False)
        batch_op.alter_column('session_id',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###
