"""empty message

Revision ID: a18a11cc7489
Revises: 790ce088a15f
Create Date: 2025-04-24 07:37:09.932673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a18a11cc7489'
down_revision = '790ce088a15f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_description', sa.String(length=500), nullable=True))
        batch_op.drop_column('product_names')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_names', mysql.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('product_description')

    # ### end Alembic commands ###
