"""empty message

Revision ID: b301f46506de
Revises: b49ee3ee4e93
Create Date: 2024-02-05 18:21:23.637599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b301f46506de'
down_revision = 'b49ee3ee4e93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sell', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delprice', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sell', schema=None) as batch_op:
        batch_op.drop_column('delprice')

    # ### end Alembic commands ###
