"""empty message

Revision ID: bdf93569e855
Revises: cf12cabbe159
Create Date: 2025-04-15 21:58:22.035734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdf93569e855'
down_revision = 'cf12cabbe159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adverts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ads_Link', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adverts', schema=None) as batch_op:
        batch_op.drop_column('ads_Link')

    # ### end Alembic commands ###
