"""empty message

Revision ID: cc8efe50325c
Revises: 6e2d37daf8a6
Create Date: 2024-02-01 08:35:23.644127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc8efe50325c'
down_revision = '6e2d37daf8a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adverts',
    sa.Column('ads_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ads_company', sa.String(length=300), nullable=False),
    sa.Column('ads_cover', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('ads_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adverts')
    # ### end Alembic commands ###
