"""empty message

Revision ID: d1dfdea1c340
Revises: 29d661d1f630
Create Date: 2025-08-06 07:37:51.640299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1dfdea1c340'
down_revision = '29d661d1f630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=128), nullable=False))
        batch_op.create_unique_constraint(None, ['session_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
