"""empty message

Revision ID: d7ea4feae2ee
Revises: d47a4485ccb8
Create Date: 2024-01-16 18:05:44.651816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ea4feae2ee'
down_revision = 'd47a4485ccb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('job_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_title', sa.String(length=300), nullable=False),
    sa.Column('job_description', sa.String(length=300), nullable=False),
    sa.Column('job_qualification', sa.String(length=300), nullable=False),
    sa.Column('employer', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    # ### end Alembic commands ###
