"""empty message

Revision ID: df09e96326b3
Revises: e9bd0e4a85dd
Create Date: 2024-02-06 13:51:33.051998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df09e96326b3'
down_revision = 'e9bd0e4a85dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('cart_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('seller_user_id', sa.Integer(), nullable=True),
    sa.Column('goods_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goods_id'], ['sell.sell_id'], ),
    sa.ForeignKeyConstraint(['seller_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('cart_id')
    )
    op.drop_table('buy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buy',
    sa.Column('buy_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('buyer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('seller_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('goods_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.user_id'], name='buy_ibfk_1'),
    sa.ForeignKeyConstraint(['goods_id'], ['sell.sell_id'], name='buy_ibfk_2'),
    sa.ForeignKeyConstraint(['seller_user_id'], ['user.user_id'], name='buy_ibfk_3'),
    sa.PrimaryKeyConstraint('buy_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('cart')
    # ### end Alembic commands ###
