"""empty message

Revision ID: e1ae2dab8930
Revises: 
Create Date: 2024-01-15 18:21:39.306968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ae2dab8930'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstname', sa.String(length=60), nullable=False),
    sa.Column('lastname', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.BigInteger(), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('sell',
    sa.Column('sell_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goods_name', sa.String(length=300), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('seller_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seller_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('sell_id')
    )
    op.create_table('buy',
    sa.Column('buy_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('seller_user_id', sa.Integer(), nullable=True),
    sa.Column('goods_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['goods_id'], ['sell.sell_id'], ),
    sa.ForeignKeyConstraint(['seller_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('buy_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buy')
    op.drop_table('sell')
    op.drop_table('user')
    op.drop_table('category')
    # ### end Alembic commands ###
